### ISSUE TITLE
There is a narrow white space on the right on mobile

### ISSUE THREAD

**Issue by Hoshitter1** [Hoshitter1/Personal-Website#15]

**Comment by Hoshitter1** [comment]
```css
html,
body{
width:100%;
overflow-x:hidden;
}
```
