### ISSUE TITLE
Fixed heading image

### ISSUE THREAD

**Issue by Hoshitter1** [Hoshitter1/Personal-Website#9]
The way the image looks changes depending on a device

**Comment by Hoshitter1** [comment]
```css
@media only screen and (max-width: 576px) and (orientation: portrait){
    .jumbotron {
        background-attachment: scroll;
    }
}
```
